language: node_js
node_js:
- 6
- 4
env:
- CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
deploy:
  provider: npm
  email: tylerfilla@gmail.com
  api_key:
    secure: EvTPsA7/4DBEzHq6XlsNtoNNVXPUABTGmN+C/XkaMCMBCVEpCllv6FbVxKCdTD2rgJoGQCvDhWCwgiEX1cnrOrFLmBgQ2f0gZ3jnd9aGeWxAlrtvwSepkIDgPHrg0hFbZtkxgezNtDaXTsV3FQ7ExbWxU+T+xPwflK60Zo+Z+UgnsKxaCiBnxdHU2OAjZT/QcIK71cd3s5pgBaMg/JrBTI0hvIhBz9r3o4wU13rB2zxsurYeU7nbByXJEyGfS+xoPy82uSd5J8VsEoKoK9eDrXF6cZiyCh5fhihynrBoF1pP6ThvViboTIBZ+eisZRU2kvliz1pzb2Z3XhBv4dyUk0H6As+zuRwdNq+OKg+ebUj83BDzXk8FpUHAyncqQHDLObc5l2Qdv4IrqWEZ5imfKjwVIQpsOinhzpOAc1NUEhzrnovsXx1AT8kiCZ5gczprrq0stWgr7zCuXrKAtB1qImcpo/e4Bu5H4l5MAfDf9Hu3cOkPMEPgdWqF1tHXJN4UgPOecQiIVYXlbjiHv390vyljpNBcgGPCreI0wb+pBt70ZXZVEMOLiUyYzKatklm7gW6NPoi/6KDFg4CPVTyv7gjiFjhpUi6TewEuWPdkWU9+ez3EEJOZCOltKivOEWq8F/jcKgIgVWS0eFABYVQ4wQHOa5oBy3k0u3yyn6kBkWA=
  on:
    tags: true
    repo: tylerfilla/node-poloniex-unofficial
